version: '3.8'
services:
  wireguard:
    image: wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/etc/wireguard
    ports:
      - "51820:51820/udp"
    environment:
      - TZ=Europe/Moscow
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    restart: unless-stopped

volumes:
  config: